version: "3.8"

networks:
  app:
    name: app
    external: true

services:
  minio:
    image: minio/minio:RELEASE.2021-04-22T15-44-28Z.hotfix.8c654a725
    container_name: minio
    restart: always
    environment:
      - MINIO_ACCESS_KEY=360cbs_ak
      - MINIO_SECRET_KEY=360cbs_sk
    networks:
      - app
    volumes:
      - /data/minio/data:/data
      - /data/minio/.minio:/root/.minio
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: ["server","/data"]

  dora:
    image: mcr.microsoft.com/dotnet/runtime-deps:6.0
    container_name: dora
    restart: always
    networks:
      - data
    volumes:
      - /data/dora/dist:/data
      - /data/dora/ffmpeg:/opt/ffmpeg
      - /etc/localtime:/etc/localtime:ro
    command:
      - sh
      - "-c"
      - "cd /data/ && chmod a+x ./ && ./MinioDORA"

